### ISSUE TITLE
[POST-AUTH] Resource-based authorization

### ISSUE THREAD

**Issue by and-ratajski** [Creoox/cx-traefik-forward-auth#4]
It is planned to implement resource-based authorization. It shall be dynamic i.e. that its specification (authorization rules) should be kept in separate file (e.g. JSON) and applied after token verification. This will allow to restrict access to resources (paths).

https://github.com/Creoox/cx-traefik-forward-auth/blob/4ffff01636e4c39a9db7104e68bb4279cfdac4bd/app/src/services/postAuth.ts#L16-L18

**Comment by CreooxTech** [comment]
Resolved with https://github.com/Creoox/cx-traefik-forward-auth/pull/10
